language: node_js
sudo: false
cache:
  directories:
    - node_modules
matrix:
  include:
    - node_js: '7'
      script: npm run pretest
      env: CI=pretest
    - node_js: '7'
      script: npm run jest -- --runInBand
      env: CI=tests 7
    - node_js: '6'
      script: npm run jest -- --runInBand
      env: CI=tests 6
    - node_js: '4'
      script: npm run jest -- --runInBand
      env: CI=tests 4
      sudo: required
    - node_js: '7'
      script: npm run jest -- --runInBand  --coverage
      env: CI=coverage
before_install:
  - npm prune
  - npm update
after_success:
  - if [ "$CI" = "coverage" ]; then cat ./.coverage/lcov.info | ./node_modules/.bin/coveralls; fi
notifications:
  webhooks:
    - https://webhooks.gitter.im/e/d763493612da45967361
