sudo: false

git:
  depth: 1

branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js

# cache node modules
cache:
  directories:
    - $HOME/.npm
    - node_modules

matrix:
  include:
    - node_js: '8'
      script: npm run pretest
      env: CI=pretest
    - node_js: '8'
      script: npm run jest -- --runInBand  --coverage
      env: CI=coverage
    - node_js: '9'
      script: npm run jest -- --runInBand
      env: CI=tests 9
    - node_js: '6'
      script: npm run jest -- --runInBand
      env: CI=tests 6
    - node_js: '4'
      script: npm run jest -- --runInBand
      env: CI=tests 4
      sudo: required

before_install:
  - npm install -g npm@latest

after_success:
  - if [ "$CI" = "coverage" ]; then cat ./.coverage/lcov.info | ./node_modules/.bin/coveralls; fi

notifications:
  webhooks:
    - https://webhooks.gitter.im/e/d763493612da45967361
