# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 0.12
    - nodejs_version: 4

version: "{build}"
build: off
deploy: off
cache: [node_modules]

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - ps: "npm test # PowerShell"
  - cmd: "npm test"
