name: Release PR

on:
  workflow_dispatch:

jobs:
  release-pr:
    uses: stylelint/.github/.github/workflows/call-release-pr.yml@2844df54744d5b95507c6df844b1422478dd3cc1 # 0.5.0
    with:
      new-version-command: npm run changeset
    permissions:
      contents: write
      pull-requests: write
