name: Release PR

on:
  workflow_dispatch:

jobs:
  release-pr:
    uses: stylelint/.github/.github/workflows/call-release-pr.yml@ce9130c0ded2a1f42fdcb64a0f1f64dd20959795 # 0.5.1
    with:
      new-version-command: npm run changeset
    permissions:
      contents: write
      pull-requests: write
