name: Release PR

on:
  workflow_dispatch:

jobs:
  release-pr:
    uses: stylelint/.github/.github/workflows/call-release-pr.yml@60889da59f384526b8185d2aa85b35620aa6bcc0 # 0.6.0
    with:
      new-version-command: npm run changeset
    permissions:
      contents: write
      pull-requests: write
